#!/bin/bash
set -euo pipefail
# shellcheck source=lib.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

# --- secretsd: session secrets broker (github.com/sjawhar/secretsd) ----------
# Mirrors installers/voxtype.sh: a Rust binary lands in bin/ behind a pinned-tag
# marker for idempotent re-runs; systemd user units are linked + enabled.
# Deliberate divergences from voxtype:
#   * a local dev build (~/Code/secretsd) is PREFERRED when newer — both of
#     Sami's machines carry the source and no release is cut yet;
#   * the socket-activated *.socket* is enabled (enabling the .service is wrong);
#   * the OpenCode plugin is registered in opencode.json via ensure_json.
SECRETSD_SRC="${HOME}/Code/secretsd"
SECRETSD_BIN="${DOTFILES_DIR}/bin/secrets"
# The plugin is owned by the secretsd repo, not this one: it speaks a versioned
# wire protocol to the broker, so it ships from the same source as the binary and
# is installed here rather than duplicated in dotfiles.
# The plugin is distributed by the secretsd repo as an installable package, so
# OpenCode fetches it from GitHub and resolves @opencode-ai/plugin itself. Nothing
# about the plugin is stored in dotfiles beyond this reference.
# The plugin is pinned to the tag matching the installed binary. They speak a
# versioned wire protocol, so they must move together -- and a moving ref like
# #main would never refresh anyway, because the package manager caches it.
SECRETSD_PLUGIN_REPO="secretsd@git+https://github.com/sjawhar/secretsd.git"
OPENCODE_JSON="${DOTFILES_DIR}/opencode/opencode.json"
secretsd_updated=0


# --- 1. Locate the binary. mise owns it: mise.toml pins a release, and mise
#        verifies the archive's GitHub build-provenance attestation on install.
#        The systemd unit runs %h/.local/bin/secrets, and a unit's minimal
#        environment cannot execute a mise shim (a shim re-execs mise), so link
#        the real installed binary there instead. ------------------------------
# mise keeps a `latest` symlink beside each installed version, so this path is
# stable across updates and needs no wrapper, shim, or symlink of our own. The
# same release also ships the systemd units next to the binary.
SECRETSD_MISE_DIR="${HOME}/.mise/installs/github-sjawhar-secretsd/latest"
SECRETSD_BIN="${SECRETSD_MISE_DIR}/bin/secrets"
if [ ! -x "$SECRETSD_BIN" ]; then
    echo "WARNING: ${SECRETSD_BIN} is absent; run 'mise install' to fetch the pinned release."
    echo "  Skipping systemd wiring until then."
    SECRETSD_BIN=""
else
    secretsd_updated=1
fi


# --- 2. Systemd user units: the repo checkout wins (edits are live on a dev
#        machine); otherwise the copy bundled in the release tarball. ----------
if [ -d "${SECRETSD_SRC}/systemd" ]; then
    UNIT_SRC="${SECRETSD_SRC}/systemd"
elif [ -d "${SECRETSD_MISE_DIR}/systemd" ]; then
    UNIT_SRC="${SECRETSD_MISE_DIR}/systemd"
else
    UNIT_SRC=""
fi

if [ -x "$SECRETSD_BIN" ] && [ -n "$UNIT_SRC" ] && \
    [ -f "${UNIT_SRC}/secretsd.service" ] && [ -f "${UNIT_SRC}/secretsd.socket" ]; then
    # The unit's ExecStart is %h/.local/bin/secrets, and the drop-in below points
    # SECRETSD_HUMAN_DIR at %h/.dotfiles/secrets.human.d.
    if [ "$DOTFILES_DIR" != "${HOME}/.dotfiles" ]; then
        echo "WARNING: DOTFILES_DIR=${DOTFILES_DIR} but the drop-in expects %h/.dotfiles;"
        echo "  secretsd would read SECRETSD_HUMAN_DIR from the wrong path. Fix the checkout location."
    fi
    mkdir -p ~/.config/systemd/user
    ensure_link "${UNIT_SRC}/secretsd.service" ~/.config/systemd/user/secretsd.service
    ensure_link "${UNIT_SRC}/secretsd.socket" ~/.config/systemd/user/secretsd.socket
    # The generic unit deliberately leaves SECRETSD_HUMAN_DIR empty and sets a
    # minimal PATH, so machine-specific locations belong in a drop-in. mise keeps
    # sops and the YubiKey plugin outside that PATH, and mise *shims* re-exec mise
    # (which fails in a unit's minimal environment), so resolve real absolute paths.
    # mise keeps a `latest` symlink beside each installed version, so these paths
    # follow the pin in mise.toml without naming a version here.
    SOPS_ABS="${HOME}/.mise/installs/sops/latest/sops"
    AGE_DIR="${HOME}/.mise/installs/github-str4d-age-plugin-yubikey/latest"
    [ -x "$SOPS_ABS" ] || SOPS_ABS="$(command -v sops || true)"
    [ -x "${AGE_DIR}/age-plugin-yubikey" ] || AGE_DIR="$(dirname "$(command -v age-plugin-yubikey || echo /nonexistent/x)")"
    mkdir -p ~/.config/systemd/user/secretsd.service.d
    {
        echo "# Generated by installers/secretsd.sh — machine-specific wiring."
        echo "[Service]"
        # The shipped unit runs %h/.local/bin/secrets; point it at the mise
        # install instead, which is where the pinned release actually lives.
        echo "ExecStart="
        # Emit %h rather than an absolute home so the same drop-in is valid on
        # every machine regardless of the account name.
        echo "ExecStart=${SECRETSD_BIN/#${HOME}/%h} serve"
        echo "Environment=SECRETSD_HUMAN_DIR=%h/.dotfiles/secrets.human.d"
        if [ -n "$SOPS_ABS" ]; then
            echo "Environment=SECRETSD_SOPS_BIN=${SOPS_ABS/#${HOME}/%h}"
        fi
        if [ -d "$AGE_DIR" ]; then
            echo "Environment=PATH=${AGE_DIR/#${HOME}/%h}:/usr/local/bin:/usr/bin"
        fi
        # Where a pcscd tunnel socket exists (the devbox reaches the YubiKey
        # through one), name it here rather than importing it into the manager
        # environment, which would not survive a manager restart.
        if [ -S "${HOME}/.pcscd/pcscd.comm" ]; then
            echo "Environment=PCSCLITE_CSOCK_NAME=%h/.pcscd/pcscd.comm"
        fi
    } > ~/.config/systemd/user/secretsd.service.d/local.conf
    if [ -z "$SOPS_ABS" ]; then
        echo "WARNING: sops not found — secretsd cannot decrypt human-tier keys until it is installed."
    fi
    if [ ! -d "$AGE_DIR" ]; then
        echo "WARNING: age-plugin-yubikey not found — human-tier decryption will fail."
    fi
    systemctl --user daemon-reload 2>/dev/null || true
    # Socket-activated: enable the .socket so the listener is up; the daemon
    # starts on first connect. --now starts the socket, not the daemon.
    systemctl --user enable --now secretsd.socket 2>/dev/null \
        || echo "NOTE: could not enable secretsd.socket (no user systemd session here?) — enable it on the target machine."

    # Devbox only: the daemon reads PCSCLITE_CSOCK_NAME from ITS OWN env to reach
    # the YubiKey over the on-demand pcscd tunnel. systemd user units do not
    # inherit the shell env, so import it when present. Absent = laptop (direct
    # YubiKey) or tunnel down (daemon fails fast with a clear message, by design).

    if [ "$secretsd_updated" -eq 1 ]; then
        # Restarting applies a replacement binary or imported manager environment
        # and deliberately clears memory-only grants; grants are never persisted.
        systemctl --user try-restart secretsd.service 2>/dev/null || true
    fi
else
    echo "secretsd: binary or units unavailable — skipping systemd wiring (install stays non-fatal)."
fi

# --- 3. Register the OpenCode plugin (idempotent). Gated on the installed file,
#        which comes from the secretsd repo or its release archive. ------------
if [ -n "$SECRETSD_BIN" ]; then
    SECRETSD_VERSION="$(basename "$(readlink -f "$SECRETSD_MISE_DIR")")"
    SECRETSD_PLUGIN="${SECRETSD_PLUGIN_REPO}#v${SECRETSD_VERSION}"
    # Replace any earlier pin so the plugin never lags the binary.
    ensure_json "$OPENCODE_JSON" \
        "$(printf '.plugin | index(\"%s\")' "$SECRETSD_PLUGIN")" \
        "$(printf '.plugin |= (map(select(startswith(\"secretsd@\") | not)) + [\"%s\"] | sort)' "$SECRETSD_PLUGIN")" \
        "Pinning secretsd OpenCode plugin to v${SECRETSD_VERSION}..."
fi
