#!/bin/bash
set -euo pipefail
# shellcheck source=lib.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

# --- secretsd: session secrets broker (github.com/sjawhar/secretsd) ----------
# Mirrors installers/voxtype.sh: mise owns the binary, systemd user units are
# linked + enabled, and re-runs are idempotent -- the drop-in carries marker
# comments so a restart happens only when something actually changed.
# Deliberate divergences from voxtype:
#   * systemd units come from a local checkout when one exists, so unit edits
#     are live on a dev machine;
#   * the socket-activated *.socket* is enabled (enabling the .service is wrong);
#   * the OpenCode plugin is registered in opencode.json via ensure_json.
# Override to point at a checkout elsewhere; only its systemd/ directory is used.
SECRETSD_SRC="${SECRETSD_SRC:-${HOME}/Code/secretsd}"
# The plugin is owned by the secretsd repo, not this one: it speaks a versioned
# wire protocol to the broker, so it ships from the same source as the binary and
# is installed here rather than duplicated in dotfiles.
# The plugin is distributed by the secretsd repo as an installable package, so
# OpenCode fetches it from GitHub and resolves @opencode-ai/plugin itself. Nothing
# about the plugin is stored in dotfiles beyond this reference.
# The plugin is pinned to the tag matching the installed binary. They speak a
# versioned wire protocol, so they must move together -- and a moving ref like
# #main would never refresh anyway, because the package manager caches it.
SECRETSD_PLUGIN_REPO="secretsd@git+https://github.com/sjawhar/secretsd.git"
OPENCODE_JSON="${DOTFILES_DIR}/opencode/opencode.json"
# Set when the binary version, the generated drop-in, or a unit file changed.
secretsd_restart_needed=0
SECRETSD_VERSION=""


# --- 1. Locate the binary. mise owns it: mise.toml pins a release, and mise
#        verifies the archive's GitHub build-provenance attestation on install.
#        The systemd unit runs %h/.local/bin/secrets, and a unit's minimal
#        environment cannot execute a mise shim (a shim re-execs mise), so link
#        the real installed binary there instead. ------------------------------
# mise keeps a `latest` symlink beside each installed version, so this path is
# stable across updates and needs no wrapper, shim, or symlink of our own. The
# same release also ships the systemd units next to the binary.
MISE_INSTALLS="${MISE_DATA_DIR:-${HOME}/.mise}/installs"
SECRETSD_MISE_DIR="${MISE_INSTALLS}/github-sjawhar-secretsd/latest"
SECRETSD_BIN="${SECRETSD_MISE_DIR}/bin/secrets"
if [ ! -x "$SECRETSD_BIN" ]; then
    echo "WARNING: ${SECRETSD_BIN} is absent; run 'mise install' to fetch the pinned release."
    echo "  Skipping systemd wiring until then."
    SECRETSD_BIN=""
else
    SECRETSD_VERSION="$(basename "$(readlink -f "$SECRETSD_MISE_DIR")")"
fi


# --- 2. Systemd user units: the repo checkout wins (edits are live on a dev
#        machine); otherwise the copy bundled in the release tarball. ----------
if [ -d "${SECRETSD_SRC}/systemd" ]; then
    UNIT_SRC="${SECRETSD_SRC}/systemd"
elif [ -d "${SECRETSD_MISE_DIR}/systemd" ]; then
    UNIT_SRC="${SECRETSD_MISE_DIR}/systemd"
else
    UNIT_SRC=""
fi

if [ -x "$SECRETSD_BIN" ] && [ -n "$UNIT_SRC" ] && \
    [ -f "${UNIT_SRC}/secretsd.service" ] && [ -f "${UNIT_SRC}/secretsd.socket" ]; then
    # Source roots live in the daemon's own config file (secretsd v2+), written
    # below from DOTFILES_DIR so a checkout outside ~/.dotfiles is configured
    # correctly instead of being pointed at a directory that does not exist.
    #
    # Write it BEFORE touching units or restarting: a v2 daemon refuses to start
    # without it, and a v1 daemon ignores it, so this order is safe in both
    # directions of an upgrade or rollback.
    mkdir -p ~/.config/secretsd
    SECRETSD_CONFIG_FILE="${HOME}/.config/secretsd/config.toml"
    {
        echo "# Generated by installers/secretsd.sh — edit the installer, not this file."
        echo "# Ordered source roots: agent-tier precedence follows declaration order,"
        echo "# local-over-shared within a root. The human tier has no precedence — a key"
        echo "# present in two roots is refused rather than silently resolved."
        echo "[source.dotfiles]"
        echo "path = \"${DOTFILES_DIR}\""
        # A private secrets repo is an optional second root: declare it only once
        # it is actually cloned, because the daemon refuses to start when a
        # configured root is missing.
        if [ -d "${HOME}/src/secrets-private/secrets.human.d" ]; then
            echo ""
            echo "[source.private]"
            echo "path = \"${HOME}/src/secrets-private\""
        fi
    } > "${SECRETSD_CONFIG_FILE}.new"
    if cmp -s "${SECRETSD_CONFIG_FILE}.new" "$SECRETSD_CONFIG_FILE" 2>/dev/null; then
        rm -f "${SECRETSD_CONFIG_FILE}.new"
    else
        mv "${SECRETSD_CONFIG_FILE}.new" "$SECRETSD_CONFIG_FILE"
        # Source roots are read at daemon startup, so a change needs a restart.
        secretsd_restart_needed=1
    fi
    mkdir -p ~/.config/systemd/user
    ensure_link "${UNIT_SRC}/secretsd.service" ~/.config/systemd/user/secretsd.service
    ensure_link "${UNIT_SRC}/secretsd.socket" ~/.config/systemd/user/secretsd.socket
    # The generic unit sets a minimal PATH, so machine-specific locations belong
    # in a drop-in. mise keeps
    # sops and the YubiKey plugin outside that PATH, and mise *shims* re-exec mise
    # (which fails in a unit's minimal environment), so resolve real absolute paths.
    # mise keeps a `latest` symlink beside each installed version, so these paths
    # follow the pin in mise.toml without naming a version here.
    SOPS_ABS="${MISE_INSTALLS}/sops/latest/sops"
    AGE_DIR="${MISE_INSTALLS}/github-str4d-age-plugin-yubikey/latest"
    [ -x "$SOPS_ABS" ] || SOPS_ABS="$(command -v sops || true)"
    [ -x "${AGE_DIR}/age-plugin-yubikey" ] || AGE_DIR="$(dirname "$(command -v age-plugin-yubikey || echo /nonexistent/x)")"
    mkdir -p ~/.config/systemd/user/secretsd.service.d
    SECRETSD_DROPIN="${HOME}/.config/systemd/user/secretsd.service.d/local.conf"
    {
        echo "# Generated by installers/secretsd.sh — machine-specific wiring."
        # ExecStart resolves through mise's `latest` symlink, so it reads the
        # same on every version. Record what `latest` points at, and the unit
        # contents, so an upgrade or a unit edit is visible in this file and
        # triggers exactly one restart instead of one per install run.
        echo "# secretsd-version: ${SECRETSD_VERSION}"
        echo "# secretsd-units: $(cat "${UNIT_SRC}/secretsd.service" "${UNIT_SRC}/secretsd.socket" | sha256sum | cut -d' ' -f1)"
        echo "[Service]"
        # The shipped unit runs %h/.local/bin/secrets; point it at the mise
        # install instead, which is where the pinned release actually lives.
        echo "ExecStart="
        # Emit %h rather than an absolute home so the same drop-in is valid on
        # every machine regardless of the account name.
        echo "ExecStart=${SECRETSD_BIN/#${HOME}/%h} serve"
        # Source roots come from ~/.config/secretsd/config.toml (written above).
        # secretsd v2 removed SECRETSD_HUMAN_DIR, but v1 *refuses to start*
        # without it, and this installer must leave a working daemon whichever
        # binary is installed -- including mid-upgrade, when the config is
        # already written but mise still has v1, and after a rollback. So emit
        # the variable exactly while the installed binary needs it. v2 ignores
        # it if a stale drop-in still carries one.
        case "$SECRETSD_VERSION" in
            1.*)
                echo "Environment=SECRETSD_HUMAN_DIR=${DOTFILES_DIR/#${HOME}/%h}/secrets.human.d"
                ;;
        esac
        if [ -n "$SOPS_ABS" ]; then
            echo "Environment=SECRETSD_SOPS_BIN=${SOPS_ABS/#${HOME}/%h}"
        fi
        if [ -d "$AGE_DIR" ]; then
            echo "Environment=PATH=${AGE_DIR/#${HOME}/%h}:/usr/local/bin:/usr/bin"
        fi
        # Where a pcscd tunnel socket exists (the devbox reaches the YubiKey
        # through one), name it here rather than importing it into the manager
        # environment, which would not survive a manager restart.
        if [ -S "${HOME}/.pcscd/pcscd.comm" ]; then
            echo "Environment=PCSCLITE_CSOCK_NAME=%h/.pcscd/pcscd.comm"
            # The tunnel socket can be live while its far end is dead, so have
            # the daemon probe the key itself before queueing a request. Gated
            # on 2.1+: only there is the probe timeout configurable, and the 2s
            # hardcoded before that is shorter than a healthy probe through the
            # tunnel (2.4-3.4s), so wiring the probe on an older daemon would
            # falsely condemn a working key.
            case "$SECRETSD_VERSION" in
                1.*|2.0.*) ;;
                *)
                    if [ -d "$AGE_DIR" ]; then
                        echo "Environment=\"SECRETSD_YUBIKEY_PROBE_CMD=${AGE_DIR/#${HOME}/%h}/age-plugin-yubikey --list\""
                        echo "Environment=SECRETSD_YUBIKEY_PROBE_TIMEOUT_SECS=10"
                    fi
                    ;;
            esac
        fi
    } > "${SECRETSD_DROPIN}.new"
    if cmp -s "${SECRETSD_DROPIN}.new" "$SECRETSD_DROPIN" 2>/dev/null; then
        rm -f "${SECRETSD_DROPIN}.new"
    else
        mv "${SECRETSD_DROPIN}.new" "$SECRETSD_DROPIN"
        secretsd_restart_needed=1
    fi
    if [ -z "$SOPS_ABS" ]; then
        echo "WARNING: sops not found — secretsd cannot decrypt human-tier keys until it is installed."
    fi
    if [ ! -d "$AGE_DIR" ]; then
        echo "WARNING: age-plugin-yubikey not found — human-tier decryption will fail."
    fi
    systemctl --user daemon-reload 2>/dev/null || true
    # Socket-activated: enable the .socket so the listener is up; the daemon
    # starts on first connect. --now starts the socket, not the daemon.
    systemctl --user enable --now secretsd.socket 2>/dev/null \
        || echo "NOTE: could not enable secretsd.socket (no user systemd session here?) — enable it on the target machine."

    # Devbox only: the daemon reads PCSCLITE_CSOCK_NAME from ITS OWN env to reach
    # the YubiKey over the on-demand pcscd tunnel. systemd user units do not
    # inherit the shell env, so import it when present. Absent = laptop (direct
    # YubiKey) or tunnel down (daemon fails fast with a clear message, by design).

    if [ "$secretsd_restart_needed" -eq 1 ]; then
        # Only when the binary version, the generated environment, or a unit
        # file actually changed -- see the marker comments in the drop-in. A
        # restart clears memory-only grants, so an unconditional one would cost
        # a YubiKey touch on every install run.
        systemctl --user try-restart secretsd.service 2>/dev/null || true
    fi
else
    echo "secretsd: binary or units unavailable — skipping systemd wiring (install stays non-fatal)."
fi

# --- 3. Register the OpenCode plugin (idempotent). Gated on the installed file,
#        which comes from the secretsd repo or its release archive. ------------
if [ -n "$SECRETSD_BIN" ]; then
    # SECRETSD_VERSION was resolved in section 1, from the same `latest` symlink.
    SECRETSD_PLUGIN="${SECRETSD_PLUGIN_REPO}#v${SECRETSD_VERSION}"
    # Replace any earlier pin so the plugin never lags the binary.
    ensure_json "$OPENCODE_JSON" \
        "$(printf '.plugin | index(\"%s\")' "$SECRETSD_PLUGIN")" \
        "$(printf '.plugin |= (map(select(startswith(\"secretsd@\") | not)) + [\"%s\"] | sort)' "$SECRETSD_PLUGIN")" \
        "Pinning secretsd OpenCode plugin to v${SECRETSD_VERSION}..."
fi
